# Generated by Django 3.1.3 on 2020-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
