# Generated by Django 3.1.3 on 2020-12-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20201206_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='likes1',
            new_name='users_likes',
        ),
    ]
