# Generated by Django 3.1.3 on 2020-12-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0014_auto_20201209_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes2',
        ),
        migrations.AddField(
            model_name='comment',
            name='users_like',
            field=models.ManyToManyField(related_name='liked_comment', through='manager.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likecommentuser',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user_table', to='manager.comment'),
        ),
    ]
