# Generated by Django 3.1.3 on 2020-12-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20201209_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users_like',
            new_name='users_likes',
        ),
    ]
