# Generated by Django 3.1.3 on 2020-12-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_book_all_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='all_stars',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users_rate',
        ),
        migrations.AddField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='RateBookUser',
        ),
    ]
