# Generated by Django 3.1.3 on 2020-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('manager', '0027_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
