# Generated by Django 3.1.3 on 2020-12-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='data',
        ),
    ]
