# Generated by Django 3.1.3 on 2020-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0041_remove_genre_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre', to='manager.Book'),
        ),
    ]
