# Generated by Django 3.1.3 on 2020-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_auto_20201227_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_book', to='manager.Genre'),
        ),
    ]
