# Generated by Django 3.1.3 on 2020-12-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_auto_20201227_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', verbose_name='Изоброжение', width_field=100),
        ),
    ]
