# Generated by Django 3.1.3 on 2020-12-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0046_auto_20201229_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
