# Generated by Django 3.1.3 on 2020-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', verbose_name='Изоброжение', width_field=100),
        ),
    ]
