# Generated by Django 3.1.3 on 2020-12-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_auto_20201229_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
