# Generated by Django 3.1.4 on 2021-01-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0053_ridbookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridbookuser',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rid_user_table', to='manager.book'),
        ),
        migrations.AlterUniqueTogether(
            name='ridbookuser',
            unique_together={('user', 'book')},
        ),
    ]
