# Generated by Django 3.1.4 on 2021-01-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_auto_20210109_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
