# Generated by Django 3.1.4 on 2021-01-16 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0055_delete_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ridbookuser',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Repozitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_account', models.CharField(max_length=100, null=True)),
                ('_github_repos', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_hab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
