# Generated by Django 3.1.4 on 2021-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repozitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
