# Generated by Django 3.1.4 on 2021-01-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0059_auto_20210113_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ridbookuser',
            unique_together=set(),
        ),
    ]
